esphome:
  name: lunalight

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret GKssid
  password: !secret GKpassword

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Luna Fallback Hotspot"
    password: "LunaPass"

captive_portal:

time:
  - platform: homeassistant

sun:
  latitude: 51.14°
  longitude: 9.414°

binary_sensor:
  - platform: gpio
    pin: D1
    name: "Luna PIR"
    device_class: motion
    id: lunapir
    on_press:
      then:
        - light.turn_on: 
            id: lunaneo
            effect: scan
        - delay: 120s
        - light.turn_off: lunaneo

sensor:
  - platform: adc
    pin: A0
    name: "LunaFoto"
    update_interval: 60s
    id: lunafoto
    
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: D6
    num_leds: 8
    name: "Luna NeoPix"
    id: lunaneo
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:

    
